### ISSUE TITLE
Feature request: scale waifu image on hover

### ISSUE THREAD

**Issue by irevenko** [Waifu-pics/waifu-frontend#1]
It would be really nice to increase web client interactivity by implementing this feature

Actually i downloaded the source code but was unable to launch it
![image](https://user-images.githubusercontent.com/44785096/117551267-e7773980-aff9-11eb-9280-2d1efbd4ee9c.png)

**Comment by JSH32** [comment]
Yeah there are cors problems(can't do anything about it because web browser is just like that), you have to disable cors for the site if you wanna use the frontend for dev.
